spring:
  application:
    name: springboot1activemq
  activemq:
  #配置自己本机地址
    broker-url: tcp://192.168.100.150:61616
    user: admin
    password: admin
  jms:
  #默认为false，若要使用发布订阅模式需要打开设置为true
    pub-sub-domain: false
server:
  port: 6206
